Develop
yura-j/java-explore-with-me pull request #3
Opened 2022-12-03 12:12 UTC by yura-j

Базовая функциональность. 
ewm core
ewm statistic

2022-12-04 08:24 UTC, yura-j reviewed
Ссылку прилепил на ветку main :(

2022-12-04 18:52 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2022-12-04 18:52 UTC, FanaticFiz commented on ewm-core/src/main/java/ru/practicum/ewm/category/CategoryService.java
> +        Page<Category> categories = categoryRepository.findAll(page);
`categories` лишнее звено, можно же сразу return.
Прям вот так:

```
    public List<CategoryDtoWithId> getAll(Integer from, Integer size) {
        return categoryRepository
                .findAll(PageRequest.of(from / size, size, Sort.by(Sort.Direction.DESC, "id")))
                .stream()
                .map(CategoryDtoMapper::fromCategory)
                .collect(Collectors.toList());
    }
```

Ну и я рекомендую.
Использовать глагол `find` в репозиториях, а глагол `get` в сервисах

2022-12-04 18:52 UTC, FanaticFiz commented on ewm-core/src/main/java/ru/practicum/ewm/compilation/CompilationMapper.java
> +    public static final DateTimeFormatter dtFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
Ты DateTimeFormatter один и тот же создаёшь в приложении 8-мь раз!!
Будь настоящим, ленивым программистом!!!
Опиши это один раз!

2022-12-04 18:52 UTC, FanaticFiz commented on ewm-core/src/main/java/ru/practicum/ewm/compilation/CompilationMapper.java
> +                : compilation.getEvents()
Это должно быть отрефакторено... нельзя писать такие тернарники...
Абсолютно никак не читаемо.

2022-12-04 18:52 UTC, FanaticFiz commented on ewm-core/src/main/java/ru/practicum/ewm/compilation/CompilationOutputDto.java
> +    public static class Category {
У нас же уже есть сущность `Category` зачем это?

Не должно быть этих вложенных классов: Category, Initiator, Event

2022-12-04 18:52 UTC, FanaticFiz commented on ewm-core/src/main/java/ru/practicum/ewm/compilation/CompilationService.java
> +                compilationRepository
несколькими строками выше запрашивалась и была получена эта сущность...
зачем мы её опять запрашиваем?

2022-12-04 18:52 UTC, FanaticFiz commented on ewm-core/src/main/java/ru/practicum/ewm/compilation/CompilationService.java
> +    private void addEventByCompilationIdAndEventId(Long compilationId, Long eventId) {
Все приватные методы должны идти после публичных.

2022-12-04 18:52 UTC, FanaticFiz commented on ewm-core/src/main/java/ru/practicum/ewm/compilation/CompilationService.java
> +        compilation.setPinned(false);
А сохранение где?
Ты достал сущность, обновил её поле, надо же вызвать: 
`compilationRepository.save(compilation)` для обновления!

2022-12-04 18:52 UTC, FanaticFiz commented on ewm-core/src/main/java/ru/practicum/ewm/controller/admin/AdminCategoryController.java
> +    ) {
У тебя пляшет стилизация код, то на новую строку перенесешь `) {` то нет
В `Java` принято так:

```
    @PostMapping
    public CategoryDtoWithId createCategory(@RequestBody @Validated(Base.class) CategoryDto dto) {
        log.info("Создана категория");

        return categoryService.create(dto);
    }
```

2022-12-04 18:52 UTC, FanaticFiz commented on ewm-core/src/main/java/ru/practicum/ewm/controller/admin/AdminCategoryController.java
> +        log.info("Создана категория");
Ты обманываешь сам себя... ничего еще не создано, а только собирается! ))
Ну и добавляй в лог больше полезной информации.

2022-12-04 18:52 UTC, FanaticFiz commented on ewm-core/src/main/java/ru/practicum/ewm/controller/admin/AdminEventsController.java
> +        List<EventState> states = null == statesParameter
Не пиши таких конструкций!

```
        List<EventState> states = null == statesParameter
                ? null
                : statesParameter
                .stream()
                .....
```


Вот так это может выглядеть: 

```
        List<EventState> states = new ArrayList<>(); // Коллекции всегда инициализируются пустыми, а не null
        if (null != statesParameter) {
            states = statesParameter
                    .stream()
                    .map(this::parseState)
                    .collect(Collectors.toList());
        }
```

2022-12-04 18:52 UTC, FanaticFiz commented on ewm-core/src/main/java/ru/practicum/ewm/controller/admin/AdminEventsController.java
> +    public static class AdminEventsSearchParameters {
Не используй вложенных классов! Вообще... в этой работе не используй.
Это вообще редкость, а ты этим прям весь код наводнил...

2022-12-04 18:52 UTC, FanaticFiz commented on ewm-core/src/main/java/ru/practicum/ewm/controller/admin/AdminEventsController.java
> +        private Optional<List<Long>> userIds;
Не должно быть Optional полей.
Его используют при возврате значения.

Просто по удаляй его тут...

2022-12-04 18:52 UTC, FanaticFiz commented on ewm-core/src/main/java/ru/practicum/ewm/error/AlreadyExistException.java
> +package ru.practicum.ewm.error;
Пакет лучше назвать `exception`

2022-12-04 18:52 UTC, FanaticFiz commented on ewm-core/src/main/java/ru/practicum/ewm/error/ErrorHandler.java
> +        log.info("404 {}", e.getMessage());
Тут произошла ошибка, логировать надо на соответствующем уровне!
И добавь еще третий параметр:
`log.info("404 {}", e.getMessage(), e);`

2022-12-04 18:52 UTC, FanaticFiz commented on ewm-core/src/main/java/ru/practicum/ewm/event/EventCreateDto.java
> +    public static class Location {
Отдельный класс!!

Посмотри, ты объявляешь класс `public static class Location` в каждом EventDto.

2022-12-04 21:54 UTC, yura-j commented on ewm-core/src/main/java/ru/practicum/ewm/error/ErrorHandler.java
> +        log.info("404 {}", e.getMessage());
Добавил

2022-12-04 21:56 UTC, yura-j commented on ewm-core/src/main/java/ru/practicum/ewm/error/AlreadyExistException.java
> +package ru.practicum.ewm.error;
переназвал

2022-12-04 22:14 UTC, yura-j commented on ewm-core/src/main/java/ru/practicum/ewm/controller/admin/AdminEventsController.java
> +        private Optional<List<Long>> userIds;
Переделал

2022-12-04 22:14 UTC, yura-j commented on ewm-core/src/main/java/ru/practicum/ewm/controller/admin/AdminEventsController.java
> +    public static class AdminEventsSearchParameters {
Убрал

2022-12-04 22:15 UTC, yura-j commented on ewm-core/src/main/java/ru/practicum/ewm/controller/admin/AdminEventsController.java
> +        List<EventState> states = null == statesParameter
Переделал

2022-12-04 22:17 UTC, yura-j commented on ewm-core/src/main/java/ru/practicum/ewm/compilation/CompilationService.java
> +        compilation.setPinned(false);
Добавил

2022-12-04 22:17 UTC, yura-j commented on ewm-core/src/main/java/ru/practicum/ewm/compilation/CompilationService.java
> +    private void addEventByCompilationIdAndEventId(Long compilationId, Long eventId) {
Перенес

2022-12-04 22:21 UTC, yura-j commented on ewm-core/src/main/java/ru/practicum/ewm/compilation/CompilationService.java
> +                compilationRepository
Поправил

2022-12-04 22:22 UTC, yura-j commented on ewm-core/src/main/java/ru/practicum/ewm/event/EventCreateDto.java
> +    public static class Location {
Прошлый ревьювер и наставник настаивали на том, чтобы Dto не были зависимы от других Dto, и реализовать это предлагалось именно через вложенные классы. Это нужно для того чтобы при изменении набора полей в одном дто случайно не поменять ответ нескольких других ендпоинтов. Поэтому просьба, не обращать на это внимание при проверке.

2022-12-04 22:23 UTC, yura-j commented on ewm-core/src/main/java/ru/practicum/ewm/compilation/CompilationOutputDto.java
> +    public static class Category {
Прошлый ревьювер и наставник настаивали на том, чтобы Dto не были зависимы от других Dto, и реализовать это предлагалось именно через вложенные классы. Это нужно для того чтобы при изменении набора полей в одном дто случайно не поменять ответ нескольких других ендпоинтов. Поэтому просьба, не обращать на это внимание при проверке.

2022-12-04 22:23 UTC, yura-j commented on ewm-core/src/main/java/ru/practicum/ewm/compilation/CompilationMapper.java
> +                : compilation.getEvents()
Отрефакторено

2022-12-04 22:23 UTC, yura-j commented on ewm-core/src/main/java/ru/practicum/ewm/compilation/CompilationMapper.java
> +    public static final DateTimeFormatter dtFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
Переделал

2022-12-04 22:23 UTC, yura-j commented on ewm-core/src/main/java/ru/practicum/ewm/category/CategoryService.java
> +        Page<Category> categories = categoryRepository.findAll(page);
Переименовал

2022-12-04 22:24 UTC, yura-j commented on ewm-core/src/main/java/ru/practicum/ewm/category/CategoryService.java
> +        Category category = categoryRepository.findById(dto.getId()).orElseThrow(NotFoundException::new);
Добавил

2022-12-04 22:24 UTC, yura-j commented on ewm-core/src/main/java/ru/practicum/ewm/category/CategoryService.java
> +                .id(savedCategory.getId())
Сделал метод в маппере и перенес в маппер

2022-12-04 22:24 UTC, yura-j commented on ewm-core/src/main/java/ru/practicum/ewm/category/CategoryService.java
> +        Category category = Category.builder()
Сделал метод в маппере и перенес в маппер

2022-12-04 22:24 UTC, yura-j commented on ewm-core/src/main/java/ru/practicum/ewm/category/Category.java
> +    private String name;
Описал

2022-12-04 22:25 UTC, yura-j commented on pom.xml
> +	<modules>
Перенес

2022-12-05 18:31 UTC, FanaticFiz approved these changes

2022-12-05 18:31 UTC, FanaticFiz commented on ewm-core/src/main/java/ru/practicum/ewm/compilation/CompilationService.java
> +        Compilation inputCompilation = Compilation
Унести в мапер...

Я не буду комментировать каждый такой случай, подумать/вспомнить, найти и исправить и в других местах кода подобное это твоя работа.

2022-12-05 18:31 UTC, FanaticFiz commented on ewm-core/src/main/java/ru/practicum/ewm/exception/ErrorHandler.java
> +        log.info("409 {}", e.getMessage(), e);
`log.info` -> `log.error` когда мы тут - это ошибка. Логируем на соответствующем уровне.

2022-12-05 19:03 UTC, merged